# Travis CI Build config

branches:
  only:
    - gh-pages

language: ruby
rvm:
    - 2.2.1

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"

before_install:
  - gem install bundler
  - bundle install

script: bundle exec jekyll build
